
server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_data
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect